import requests, json
from prometheus_client import Gauge, generate_latest, REGISTRY
from prometheus_client.core import CollectorRegistry
from prometheus_client import MetricsHandler
from http.server import BaseHTTPRequestHandler, HTTPServer

tradeables = ["LTC", "ETH", "XRP", "DOGE", "USDT"]

crypto_trade_routes = Gauge('crypto_trade_routes', 'Trade routes and profitability by type', ['pair'])

def fetch_btc_to_eth_conversion_rate():
    rawdata = requests.get('https://api.coingate.com/v2/rates').json()
    valuablepairs = {}

    for firsthop in tradeables:
        for secondhop in tradeables:
            if secondhop == firsthop: continue
            priceindex2 = 1.0
            priceindex2 = priceindex2 * float(rawdata["merchant"]["BTC"][firsthop])
            priceindex2 = priceindex2 * float(rawdata["merchant"][firsthop][secondhop])
            priceindex2 = priceindex2 * float(rawdata["merchant"][secondhop]["BTC"])
            valuablepairs[str("BTC_" + firsthop + "_" + secondhop + "_BTC")] = priceindex2
            for thirdhop in tradeables:
                if thirdhop == firsthop: continue
                if thirdhop == secondhop: continue
                priceindex3 = 1.0
                priceindex3 = priceindex3 * float(rawdata["merchant"]["BTC"][firsthop])
                priceindex3 = priceindex3 * float(rawdata["merchant"][firsthop][secondhop])
                priceindex3 = priceindex3 * float(rawdata["merchant"][secondhop][thirdhop])
                priceindex3 = priceindex3 * float(rawdata["merchant"][thirdhop]["BTC"])
                valuablepairs[str("BTC_" + firsthop + "_" + secondhop + "_" + thirdhop + "_BTC")] = priceindex3
                for fourthhop in tradeables:
                    if fourthhop == firsthop: continue
                    if fourthhop == secondhop: continue
                    if fourthhop == thirdhop: continue
                    priceindex4 = 1.0
                    priceindex4 = priceindex4 * float(rawdata["merchant"]["BTC"][firsthop])
                    priceindex4 = priceindex4 * float(rawdata["merchant"][firsthop][secondhop])
                    priceindex4 = priceindex4 * float(rawdata["merchant"][secondhop][thirdhop])
                    priceindex4 = priceindex4 * float(rawdata["merchant"][thirdhop][fourthhop])
                    priceindex4 = priceindex4 * float(rawdata["merchant"][fourthhop]["BTC"])
                    valuablepairs[str("BTC_" + firsthop + "_" + secondhop + "_" + thirdhop + "_" + fourthhop + "_BTC")] = priceindex4
                    
    crypto_trade_routes.labels(pair='BTC_USDT_LTC_ETH_DOGE_BTC').set(valuablepairs.get('BTC_USDT_LTC_ETH_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_LTC_ETH_DOGE_BTC').set(valuablepairs.get('BTC_XRP_LTC_ETH_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_ETH_XRP_DOGE_BTC').set(valuablepairs.get('BTC_LTC_ETH_XRP_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_ETH_USDT_DOGE_BTC').set(valuablepairs.get('BTC_LTC_ETH_USDT_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_ETH_DOGE_BTC').set(valuablepairs.get('BTC_LTC_ETH_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_XRP_ETH_DOGE_BTC').set(valuablepairs.get('BTC_USDT_XRP_ETH_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_ETH_XRP_DOGE_BTC').set(valuablepairs.get('BTC_USDT_ETH_XRP_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_ETH_DOGE_BTC').set(valuablepairs.get('BTC_USDT_ETH_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_XRP_LTC_DOGE_BTC').set(valuablepairs.get('BTC_USDT_XRP_LTC_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_XRP_DOGE_BTC').set(valuablepairs.get('BTC_USDT_XRP_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_DOGE_BTC').set(valuablepairs.get('BTC_USDT_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_LTC_DOGE_BTC').set(valuablepairs.get('BTC_USDT_LTC_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_LTC_XRP_DOGE_BTC').set(valuablepairs.get('BTC_USDT_LTC_XRP_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_ETH_USDT_DOGE_BTC').set(valuablepairs.get('BTC_XRP_ETH_USDT_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_ETH_DOGE_BTC').set(valuablepairs.get('BTC_XRP_ETH_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_USDT_ETH_DOGE_BTC').set(valuablepairs.get('BTC_XRP_USDT_ETH_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_LTC_USDT_DOGE_BTC').set(valuablepairs.get('BTC_XRP_LTC_USDT_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_LTC_DOGE_BTC').set(valuablepairs.get('BTC_XRP_LTC_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_USDT_DOGE_BTC').set(valuablepairs.get('BTC_XRP_USDT_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_DOGE_BTC').set(valuablepairs.get('BTC_XRP_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_USDT_LTC_DOGE_BTC').set(valuablepairs.get('BTC_XRP_USDT_LTC_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_XRP_ETH_DOGE_BTC').set(valuablepairs.get('BTC_LTC_XRP_ETH_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_USDT_ETH_DOGE_BTC').set(valuablepairs.get('BTC_LTC_USDT_ETH_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_USDT_XRP_DOGE_BTC').set(valuablepairs.get('BTC_LTC_USDT_XRP_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_USDT_DOGE_BTC').set(valuablepairs.get('BTC_LTC_USDT_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_DOGE_BTC').set(valuablepairs.get('BTC_LTC_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_XRP_USDT_DOGE_BTC').set(valuablepairs.get('BTC_LTC_XRP_USDT_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_XRP_DOGE_BTC').set(valuablepairs.get('BTC_LTC_XRP_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_DOGE_LTC_ETH_BTC').set(valuablepairs.get('BTC_USDT_DOGE_LTC_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_XRP_LTC_ETH_BTC').set(valuablepairs.get('BTC_USDT_XRP_LTC_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_LTC_ETH_BTC').set(valuablepairs.get('BTC_USDT_LTC_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_DOGE_LTC_ETH_BTC').set(valuablepairs.get('BTC_XRP_DOGE_LTC_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_LTC_ETH_BTC').set(valuablepairs.get('BTC_XRP_LTC_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_USDT_LTC_ETH_BTC').set(valuablepairs.get('BTC_XRP_USDT_LTC_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_XRP_LTC_DOGE_BTC').set(valuablepairs.get('BTC_ETH_XRP_LTC_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_XRP_USDT_DOGE_BTC').set(valuablepairs.get('BTC_ETH_XRP_USDT_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_XRP_DOGE_BTC').set(valuablepairs.get('BTC_ETH_XRP_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_USDT_XRP_DOGE_BTC').set(valuablepairs.get('BTC_ETH_USDT_XRP_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_USDT_DOGE_BTC').set(valuablepairs.get('BTC_ETH_USDT_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_USDT_LTC_DOGE_BTC').set(valuablepairs.get('BTC_ETH_USDT_LTC_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_DOGE_BTC').set(valuablepairs.get('BTC_ETH_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_ETH_BTC').set(valuablepairs.get('BTC_LTC_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_LTC_ETH_XRP_BTC').set(valuablepairs.get('BTC_USDT_LTC_ETH_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_ETH_XRP_BTC').set(valuablepairs.get('BTC_LTC_ETH_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_ETH_DOGE_XRP_BTC').set(valuablepairs.get('BTC_LTC_ETH_DOGE_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_ETH_USDT_XRP_BTC').set(valuablepairs.get('BTC_LTC_ETH_USDT_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_LTC_ETH_USDT_BTC').set(valuablepairs.get('BTC_XRP_LTC_ETH_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_ETH_LTC_DOGE_BTC').set(valuablepairs.get('BTC_USDT_ETH_LTC_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_ETH_LTC_DOGE_BTC').set(valuablepairs.get('BTC_XRP_ETH_LTC_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_ETH_XRP_USDT_BTC').set(valuablepairs.get('BTC_LTC_ETH_XRP_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_ETH_USDT_BTC').set(valuablepairs.get('BTC_LTC_ETH_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_ETH_DOGE_USDT_BTC').set(valuablepairs.get('BTC_LTC_ETH_DOGE_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_XRP_DOGE_ETH_BTC').set(valuablepairs.get('BTC_USDT_XRP_DOGE_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_DOGE_ETH_BTC').set(valuablepairs.get('BTC_USDT_DOGE_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_LTC_DOGE_ETH_BTC').set(valuablepairs.get('BTC_USDT_LTC_DOGE_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_DOGE_XRP_ETH_BTC').set(valuablepairs.get('BTC_USDT_DOGE_XRP_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_XRP_ETH_BTC').set(valuablepairs.get('BTC_USDT_XRP_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_LTC_DOGE_ETH_BTC').set(valuablepairs.get('BTC_XRP_LTC_DOGE_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_USDT_DOGE_ETH_BTC').set(valuablepairs.get('BTC_XRP_USDT_DOGE_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_DOGE_ETH_BTC').set(valuablepairs.get('BTC_XRP_DOGE_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_LTC_XRP_ETH_BTC').set(valuablepairs.get('BTC_USDT_LTC_XRP_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_ETH_BTC').set(valuablepairs.get('BTC_USDT_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_ETH_BTC').set(valuablepairs.get('BTC_XRP_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_LTC_USDT_ETH_BTC').set(valuablepairs.get('BTC_XRP_LTC_USDT_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_USDT_ETH_BTC').set(valuablepairs.get('BTC_XRP_USDT_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_DOGE_USDT_ETH_BTC').set(valuablepairs.get('BTC_XRP_DOGE_USDT_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_LTC_USDT_DOGE_BTC').set(valuablepairs.get('BTC_ETH_LTC_USDT_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_LTC_DOGE_BTC').set(valuablepairs.get('BTC_ETH_LTC_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_LTC_XRP_DOGE_BTC').set(valuablepairs.get('BTC_ETH_LTC_XRP_DOGE_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_ETH_XRP_LTC_BTC').set(valuablepairs.get('BTC_USDT_ETH_XRP_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_ETH_DOGE_LTC_BTC').set(valuablepairs.get('BTC_USDT_ETH_DOGE_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_XRP_DOGE_LTC_BTC').set(valuablepairs.get('BTC_USDT_XRP_DOGE_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_DOGE_XRP_LTC_BTC').set(valuablepairs.get('BTC_USDT_DOGE_XRP_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_DOGE_LTC_BTC').set(valuablepairs.get('BTC_USDT_DOGE_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_XRP_LTC_BTC').set(valuablepairs.get('BTC_USDT_XRP_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_LTC_BTC').set(valuablepairs.get('BTC_USDT_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_ETH_DOGE_LTC_BTC').set(valuablepairs.get('BTC_XRP_ETH_DOGE_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_ETH_USDT_LTC_BTC').set(valuablepairs.get('BTC_XRP_ETH_USDT_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_USDT_DOGE_LTC_BTC').set(valuablepairs.get('BTC_XRP_USDT_DOGE_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_DOGE_LTC_BTC').set(valuablepairs.get('BTC_XRP_DOGE_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_LTC_BTC').set(valuablepairs.get('BTC_XRP_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_USDT_LTC_BTC').set(valuablepairs.get('BTC_XRP_USDT_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_DOGE_USDT_LTC_BTC').set(valuablepairs.get('BTC_XRP_DOGE_USDT_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_USDT_DOGE_ETH_BTC').set(valuablepairs.get('BTC_LTC_USDT_DOGE_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_DOGE_ETH_BTC').set(valuablepairs.get('BTC_LTC_DOGE_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_XRP_DOGE_ETH_BTC').set(valuablepairs.get('BTC_LTC_XRP_DOGE_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_DOGE_XRP_ETH_BTC').set(valuablepairs.get('BTC_LTC_DOGE_XRP_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_USDT_XRP_ETH_BTC').set(valuablepairs.get('BTC_LTC_USDT_XRP_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_XRP_ETH_BTC').set(valuablepairs.get('BTC_LTC_XRP_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_USDT_ETH_BTC').set(valuablepairs.get('BTC_LTC_USDT_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_DOGE_USDT_ETH_BTC').set(valuablepairs.get('BTC_LTC_DOGE_USDT_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_XRP_USDT_ETH_BTC').set(valuablepairs.get('BTC_LTC_XRP_USDT_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_DOGE_ETH_XRP_BTC').set(valuablepairs.get('BTC_USDT_DOGE_ETH_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_ETH_XRP_BTC').set(valuablepairs.get('BTC_USDT_ETH_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_ETH_DOGE_XRP_BTC').set(valuablepairs.get('BTC_USDT_ETH_DOGE_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_DOGE_XRP_BTC').set(valuablepairs.get('BTC_USDT_DOGE_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_DOGE_LTC_XRP_BTC').set(valuablepairs.get('BTC_USDT_DOGE_LTC_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_LTC_DOGE_XRP_BTC').set(valuablepairs.get('BTC_USDT_LTC_DOGE_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_XRP_BTC').set(valuablepairs.get('BTC_USDT_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_LTC_XRP_BTC').set(valuablepairs.get('BTC_USDT_LTC_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_DOGE_ETH_XRP_BTC').set(valuablepairs.get('BTC_LTC_DOGE_ETH_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_XRP_DOGE_LTC_BTC').set(valuablepairs.get('BTC_ETH_XRP_DOGE_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_XRP_LTC_BTC').set(valuablepairs.get('BTC_ETH_XRP_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_USDT_DOGE_LTC_BTC').set(valuablepairs.get('BTC_ETH_USDT_DOGE_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_DOGE_XRP_LTC_BTC').set(valuablepairs.get('BTC_ETH_DOGE_XRP_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_DOGE_LTC_BTC').set(valuablepairs.get('BTC_ETH_DOGE_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_XRP_USDT_LTC_BTC').set(valuablepairs.get('BTC_ETH_XRP_USDT_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_USDT_XRP_LTC_BTC').set(valuablepairs.get('BTC_ETH_USDT_XRP_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_USDT_LTC_BTC').set(valuablepairs.get('BTC_ETH_USDT_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_DOGE_USDT_LTC_BTC').set(valuablepairs.get('BTC_ETH_DOGE_USDT_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_USDT_ETH_XRP_BTC').set(valuablepairs.get('BTC_LTC_USDT_ETH_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_USDT_DOGE_XRP_BTC').set(valuablepairs.get('BTC_LTC_USDT_DOGE_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_DOGE_XRP_BTC').set(valuablepairs.get('BTC_LTC_DOGE_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_USDT_XRP_BTC').set(valuablepairs.get('BTC_LTC_USDT_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_DOGE_USDT_XRP_BTC').set(valuablepairs.get('BTC_LTC_DOGE_USDT_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_XRP_BTC').set(valuablepairs.get('BTC_LTC_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_DOGE_ETH_USDT_BTC').set(valuablepairs.get('BTC_XRP_DOGE_ETH_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_ETH_USDT_BTC').set(valuablepairs.get('BTC_XRP_ETH_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_ETH_DOGE_USDT_BTC').set(valuablepairs.get('BTC_XRP_ETH_DOGE_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_DOGE_LTC_USDT_BTC').set(valuablepairs.get('BTC_XRP_DOGE_LTC_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_LTC_USDT_BTC').set(valuablepairs.get('BTC_XRP_LTC_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_LTC_DOGE_USDT_BTC').set(valuablepairs.get('BTC_XRP_LTC_DOGE_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_USDT_BTC').set(valuablepairs.get('BTC_XRP_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_DOGE_USDT_BTC').set(valuablepairs.get('BTC_XRP_DOGE_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_XRP_LTC_ETH_BTC').set(valuablepairs.get('BTC_DOGE_XRP_LTC_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_LTC_ETH_BTC').set(valuablepairs.get('BTC_DOGE_LTC_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_USDT_LTC_ETH_BTC').set(valuablepairs.get('BTC_DOGE_USDT_LTC_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_XRP_BTC').set(valuablepairs.get('BTC_ETH_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_USDT_DOGE_XRP_BTC').set(valuablepairs.get('BTC_ETH_USDT_DOGE_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_DOGE_XRP_BTC').set(valuablepairs.get('BTC_ETH_DOGE_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_DOGE_LTC_XRP_BTC').set(valuablepairs.get('BTC_ETH_DOGE_LTC_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_USDT_XRP_BTC').set(valuablepairs.get('BTC_ETH_USDT_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_DOGE_USDT_XRP_BTC').set(valuablepairs.get('BTC_ETH_DOGE_USDT_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_USDT_LTC_XRP_BTC').set(valuablepairs.get('BTC_ETH_USDT_LTC_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_DOGE_ETH_USDT_BTC').set(valuablepairs.get('BTC_LTC_DOGE_ETH_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_XRP_ETH_USDT_BTC').set(valuablepairs.get('BTC_LTC_XRP_ETH_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_DOGE_XRP_USDT_BTC').set(valuablepairs.get('BTC_LTC_DOGE_XRP_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_USDT_BTC').set(valuablepairs.get('BTC_LTC_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_DOGE_USDT_BTC').set(valuablepairs.get('BTC_LTC_DOGE_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_XRP_USDT_BTC').set(valuablepairs.get('BTC_LTC_XRP_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_LTC_XRP_DOGE_USDT_BTC').set(valuablepairs.get('BTC_LTC_XRP_DOGE_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_XRP_LTC_USDT_BTC').set(valuablepairs.get('BTC_ETH_XRP_LTC_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_DOGE_LTC_USDT_BTC').set(valuablepairs.get('BTC_ETH_DOGE_LTC_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_XRP_USDT_BTC').set(valuablepairs.get('BTC_ETH_XRP_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_XRP_DOGE_USDT_BTC').set(valuablepairs.get('BTC_ETH_XRP_DOGE_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_DOGE_XRP_USDT_BTC').set(valuablepairs.get('BTC_ETH_DOGE_XRP_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_USDT_BTC').set(valuablepairs.get('BTC_ETH_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_DOGE_USDT_BTC').set(valuablepairs.get('BTC_ETH_DOGE_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_LTC_ETH_XRP_BTC').set(valuablepairs.get('BTC_DOGE_LTC_ETH_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_DOGE_ETH_LTC_BTC').set(valuablepairs.get('BTC_USDT_DOGE_ETH_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_XRP_ETH_LTC_BTC').set(valuablepairs.get('BTC_USDT_XRP_ETH_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_DOGE_ETH_LTC_BTC').set(valuablepairs.get('BTC_XRP_DOGE_ETH_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_ETH_LTC_BTC').set(valuablepairs.get('BTC_USDT_ETH_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_ETH_LTC_BTC').set(valuablepairs.get('BTC_XRP_ETH_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_USDT_ETH_LTC_BTC').set(valuablepairs.get('BTC_XRP_USDT_ETH_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_LTC_ETH_USDT_BTC').set(valuablepairs.get('BTC_DOGE_LTC_ETH_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_USDT_ETH_LTC_XRP_BTC').set(valuablepairs.get('BTC_USDT_ETH_LTC_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_LTC_BTC').set(valuablepairs.get('BTC_ETH_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_XRP_ETH_LTC_USDT_BTC').set(valuablepairs.get('BTC_XRP_ETH_LTC_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_ETH_BTC').set(valuablepairs.get('BTC_DOGE_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_XRP_ETH_BTC').set(valuablepairs.get('BTC_DOGE_XRP_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_LTC_XRP_ETH_BTC').set(valuablepairs.get('BTC_DOGE_LTC_XRP_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_USDT_XRP_ETH_BTC').set(valuablepairs.get('BTC_DOGE_USDT_XRP_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_LTC_USDT_ETH_BTC').set(valuablepairs.get('BTC_DOGE_LTC_USDT_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_XRP_USDT_ETH_BTC').set(valuablepairs.get('BTC_DOGE_XRP_USDT_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_USDT_ETH_BTC').set(valuablepairs.get('BTC_DOGE_USDT_ETH_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_LTC_DOGE_XRP_BTC').set(valuablepairs.get('BTC_ETH_LTC_DOGE_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_LTC_USDT_XRP_BTC').set(valuablepairs.get('BTC_ETH_LTC_USDT_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_LTC_XRP_BTC').set(valuablepairs.get('BTC_ETH_LTC_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_ETH_XRP_LTC_BTC').set(valuablepairs.get('BTC_DOGE_ETH_XRP_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_ETH_USDT_LTC_BTC').set(valuablepairs.get('BTC_DOGE_ETH_USDT_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_XRP_LTC_BTC').set(valuablepairs.get('BTC_DOGE_XRP_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_LTC_BTC').set(valuablepairs.get('BTC_DOGE_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_XRP_USDT_LTC_BTC').set(valuablepairs.get('BTC_DOGE_XRP_USDT_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_USDT_XRP_LTC_BTC').set(valuablepairs.get('BTC_DOGE_USDT_XRP_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_USDT_LTC_BTC').set(valuablepairs.get('BTC_DOGE_USDT_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_ETH_XRP_BTC').set(valuablepairs.get('BTC_DOGE_ETH_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_ETH_USDT_XRP_BTC').set(valuablepairs.get('BTC_DOGE_ETH_USDT_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_LTC_USDT_BTC').set(valuablepairs.get('BTC_ETH_LTC_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_LTC_DOGE_USDT_BTC').set(valuablepairs.get('BTC_ETH_LTC_DOGE_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_ETH_LTC_XRP_USDT_BTC').set(valuablepairs.get('BTC_ETH_LTC_XRP_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_USDT_ETH_XRP_BTC').set(valuablepairs.get('BTC_DOGE_USDT_ETH_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_LTC_USDT_XRP_BTC').set(valuablepairs.get('BTC_DOGE_LTC_USDT_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_XRP_BTC').set(valuablepairs.get('BTC_DOGE_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_LTC_XRP_BTC').set(valuablepairs.get('BTC_DOGE_LTC_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_USDT_XRP_BTC').set(valuablepairs.get('BTC_DOGE_USDT_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_USDT_LTC_XRP_BTC').set(valuablepairs.get('BTC_DOGE_USDT_LTC_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_ETH_XRP_USDT_BTC').set(valuablepairs.get('BTC_DOGE_ETH_XRP_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_ETH_USDT_BTC').set(valuablepairs.get('BTC_DOGE_ETH_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_XRP_ETH_USDT_BTC').set(valuablepairs.get('BTC_DOGE_XRP_ETH_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_XRP_LTC_USDT_BTC').set(valuablepairs.get('BTC_DOGE_XRP_LTC_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_LTC_USDT_BTC').set(valuablepairs.get('BTC_DOGE_LTC_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_XRP_USDT_BTC').set(valuablepairs.get('BTC_DOGE_XRP_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_LTC_XRP_USDT_BTC').set(valuablepairs.get('BTC_DOGE_LTC_XRP_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_USDT_BTC').set(valuablepairs.get('BTC_DOGE_USDT_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_ETH_LTC_BTC').set(valuablepairs.get('BTC_DOGE_ETH_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_XRP_ETH_LTC_BTC').set(valuablepairs.get('BTC_DOGE_XRP_ETH_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_USDT_ETH_LTC_BTC').set(valuablepairs.get('BTC_DOGE_USDT_ETH_LTC_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_ETH_LTC_XRP_BTC').set(valuablepairs.get('BTC_DOGE_ETH_LTC_XRP_BTC'))
    crypto_trade_routes.labels(pair='BTC_DOGE_ETH_LTC_USDT_BTC').set(valuablepairs.get('BTC_DOGE_ETH_LTC_USDT_BTC'))

class CustomMetricsHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        """Handles GET requests for Prometheus scraping."""
        # Fetch the latest BTC to ETH conversion rate
        fetch_btc_to_eth_conversion_rate()
        
        # Set HTTP response headers
        self.send_response(200)
        self.send_header("Content-Type", "text/plain; version=0.0.4; charset=utf-8")
        self.end_headers()
        
        # Output the latest metrics to the HTTP response
        output = generate_latest(REGISTRY)
        self.wfile.write(output)

if __name__ == "__main__":
    # Start an HTTP server to serve the metrics on port 8069
    server = HTTPServer(('0.0.0.0', 8069), CustomMetricsHandler)
    print("Starting server on port 8069...")
    server.serve_forever()